### ISSUE TITLE
Audit error messages

### ISSUE THREAD

**Issue by seantking** [cosmos/interchain-accounts#26]

**Comment by colin-axner** [comment]
Noticed an incorrect error in the [ibc-account](https://github.com/cosmos/interchain-accounts/blob/b8b76c0b795bb16849e12fd17b6ade0c460ffc27/x/ibc-account/module.go#L212) module as well

It is useful to just do a sweep of all the error messages in this repo. I did the same for ibc-go before launch and it can help to clean up a lot of out dated, incorrect or bad error messages
