### ISSUE TITLE
Manual QA 

### ISSUE THREAD

**Issue by seantking** [cosmos/interchain-accounts#73]
We need to test: 

- [x] Test the allowlist functionality for messages an ICA can execute (this is already done I guess) 
- [x] Multiple controller chains creating accounts on a single host chain + executing transactions 
- [x] Testing the controller/host enabled flags to ensure they're working (chain can be controller but not host etc) 

Hermes: 

- [x] Hermes can successfully listen for `OnChanOpenInit` events. This is currently not working and seems to be a core IBC issue.

**Comment by damiannolan** [comment]
- Allowlist functionality confirmed
- Host/Controller enabled flags functionality confirmed, tested various combinations such as:
  - ChainA (controller: true, host: true) + ChainB (controller: true, host: true)
  - ChainA (controller: false, host: false) + ChainB (controller: false, host: false)
  - ChainA (controller: true, host: false) + ChainB (controller: false, host: false)
  - ChainA (controller: true, host: false) + ChainB (controller: false, host: true)
- Multiple controller chains (multiple interchain accounts) on a single host chain functionality confirmed; e.g. ChainA and ChainC control interchain accounts hosted on ChainB

**Comment by damiannolan** [comment]
> Hermes can successfully listen for OnChanOpenInit events. This is currently not working and seems to be a core IBC issue.

This has been resolved by [ibc-go #624](https://github.com/cosmos/ibc-go/pull/624)
